# -*- coding: utf-8 -*-
"""EjerciciosSemana1Clase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P9mERrOLiupiK01HfK9FZGlKX4yYfI3t

Ejercicio 2


Rebotes. Una pelota de goma es arrojada desde una altura de 100 metros y cada vez que toca el piso salta 3/5 de la altura desde la que cayó. Escribí un programa/script que imprima una tabla mostrando las alturas que alcanza en cada uno de sus primeros diez rebotes
"""

rebotes = [1,2,3,4,5,6,7,8,9,10]
i = 0
alturaInicial = 100

for i in rebotes :
  alturaFinal = alturaInicial * 3 / 5
  alturaInicial = alturaFinal 

  print (alturaFinal)

"""Ejercicio 3

Hacer un programa/script que le pregunte al usuario en qué año ocurrió el descubrimiento de América (1492), y que le responda si acertó o no.


"""

respuesta = input('En que año se descubrio america?: ')
respuesta = int (respuesta)

if respuesta == 1492 :
  print ("La respuesta es CORRECTA")
else:
  print ("La respuesta es INCORRECTA")

"""Ejercicio 4

Suponé que tenes $100 dólares, que podés invertir con un 10% de retorno anual. Después de un año, esto es 100 x 1.1 = 110 dólares y luego de dos años es 100 x 1.1 x 1.1 = 121. Escribí el código para calcular cuanto dinero vas a tener al cabo de 7 años, e imprimí el resultado.
"""

montoInicial = 100

anios = 7
i = 0

while i < anios :
  montoFinal = montoInicial * 1.1
  montoInicial = montoFinal
  i = i +1

print (montoFinal)

"""Ejercicio 5

La hipoteca de David. David solicitó un crédito a 30 años para comprar una vivienda, con una tasa fija nominal anual del 5%. Pidió 500000 al banco y acordó un pago mensual fijo de $2684,11.

Supongamos que David adelanta pagos extra de 1000 por mes durante los primeros 12 meses de la hipoteca. Modificá abajo el programa para incorporar estos pagos extra y que imprima el monto total pagado junto con la cantidad de meses requeridos. Debería dar un pago total de 929965.62 en 342 meses.

Pregunta adicional: investigar que hace la función round. Qué hace el parámetro 2 en esta función?

¿Cuánto pagaría David si agrega 1000 por mes durante cuatro años, comenzando en el sexto año de la hipoteca (es decir, luego de 5 años)? 
"""

tasaFija : 0.05
creditoInicial = 500000

pagoMensual = 2684.11