# -*- coding: utf-8 -*-
"""EjerciciosSemana1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kpnYFDzhbsXyWFaQu6QIUsFFsSzwR7l7

# Ejercicios – Semana 1

Conjunto de ejercicios simples para practicar lo aprendido en la Semana 1.

## Ejercicio 1:

> a. Crea 3 variables, una entera, una flotante y una cadena de texto.

> b. Imprime cada una de las variables en la consola.

> c. Crea una variable booleana y asignale un valor.

> d. Imprime la variable booleana en la consola.
"""

# Declaro las tres variables, con sus respectivos tipos aclarados en sus nombres

variable_entera = 10

variable_flotante = 12.3

variable_cadena = 'Ahora'

print (variable_entera, '\n' , variable_flotante, '\n' , variable_cadena)

variable_booleana = True

print ('\n', variable_booleana)

"""## Ejercicio 2:

> a.    Crea una variable entera llamada edad y asígnale un valor.

> b.    Crea una variable flotante llamada altura y asígnale un valor.

> c.    Crea una variable de texto llamada nombre y asígnale un valor.

> d.    Crea una variable booleana llamada soltero y asígnale un valor.

> e.    Imprime en la consola la edad, la altura, el nombre y el estado civil (soltero o no soltero).

> f.    Crea una variable llamada todos_datos que sea una lista que contenga la edad, la altura, el nombre y el estado civil.

> g.    Imprime la lista todos_datos en la consola.
"""

edad = 25
altura = 1.72
nombre = 'Alexis'
soltero = True

print (edad, altura, nombre, soltero)

todos_datos = [edad, altura, nombre, soltero]

print (todos_datos)

"""## Ejercicio 3:


*El índice de masa corporal (IMC) se puede calcular utilizando la siguiente fórmula:*

> *IMC = P / A^2*

> *donde P es el peso de la persona en kilogramos y A es la altura de la misma persona en metros. La fórmula resulta en un número que se utiliza para determinar si una persona está en un peso saludable o no.* 

*Un IMC normal se encuentra entre 18.5 y 24.9 kg/m^2. Un IMC menor a 18.5 kg/m^2 se considera bajo peso, mientras que un IMC mayor a 25 kg/m^2 se considera sobrepeso. Un IMC mayor a 30 kg/m^2 se considera obesidad. Sin embargo, estos valores son solo una guía y no son válidos para todas las personas, especialmente aquellas con una gran cantidad de músculo o deportistas.*

**Crea un programa que te pida (usando input()) las siguientes informaciones: nombre, edad, peso en kg y altura en m y que te devuelva el nombre, la edad y el índice de masa corporal de esa persona.**


*PISTA: input() siempre devuelve siempre una cadena*
"""

# input() promptea al usuario y guarda esa variable COMO UNA CADENA (str).
nombre = input('¿Nombre?: ')

edad_str = input('¿Edad?: ')
edad = int(edad_str)  # Como input guarda la variable como cadena, hay que 'castearla' (convertir su tipo) a entero, con la funcion int() (int=integer=entero)
                      # ¿Que pasa si el usuario introduce una palabra en vez de un numero?

#... (ahora podes seguir con el código....)

peso_str = input('¿Peso (kg)?: ')
peso = float(peso_str)
altura_str = input('¿Altura (metros)?: ')
altura = float(altura_str)
indiceMasaCorporal = peso / (altura**2)

print(nombre, 'de ', edad, ' años de edad posee un indice de masa corporal de: ', indiceMasaCorporal )

"""## Ejercicio 4:

Crea un código que declare una variable con el número 5 elevado a la cuarta potencia. Luego que escriba en pantalla un mensaje que diga el tipo de variable declarada. Luego hacer lo mismo, pero cambiando el exponente a 1/2 y a una potencia negativa.  
"""

num1 = 5**4
print ('num1 es una variable del tipo ', type(num1), ' y su valor es 5¨4 = ', num1)

num2 = 5**(1/2)
print ('num2 es una variable del tipo ', type(num2), ' y su valor es 5¨1/2 = ', num2)

num3 = 5**(-2)
print ('num3 es una variable del tipo ', type(num3), ' y su valor es 5¨-1 = ', num3)

"""## Ejercicio 5:

Crea un código que tome como parámetro una frase y sea capaz de contar el número de palabras que contiene. Haga un test con la frase: "Me gusta estudiar python en la UNSAM". 

Y si queremos contar los caracteres incluyendo los espacios. ¿Cómo seria?

Prueba con otras frases, para eso podes usar la funcion de ingreso de valores por teclado. 
"""

frase1 = 'Me gusta estudiar python en la UNSAM' 
print ('La frase 1 contiene ', len(frase1.split()) , 'palabras')
print ('La frase 1 contene ', len(frase1), 'caracteres incluyendo los espacios')

frase2 = input('Ingrese una frase: ')
print ('La frase 2 contiene ', len(frase2.split()) , 'palabras')
print ('La frase 2 contene ', len(frase2), 'caracteres incluyendo los espacios')

"""## Ejercicio 6:

Escriba un programa que reciba dos números y los compare dando como resultado verdadero o falso ante la frase: El primer número es menor que el segundo. 
"""

num1_str = input('Ingrese el primer numero: ')
num1 = int(num1_str)

num2_str = input('Ingrese el segundo numero: ')
num2 = int(num2_str)

if (num1<num2):
  print("El primer número es menor que el segundo.")
  print(True)
else:
  print("El primer número no es menor que el segundo.")
  print(False)

"""## Ejercicio 7:

Cree un programa en python que calcule el promedio entre 2 notas.
"""

nota1_str = input('Ingrese la primer nota: ')
nota1 = int(nota1_str)

nota2_str = input('Ingrese la segunda nota: ')
nota2 = int(nota2_str)

promedio = nota1 / nota2

print ("El promedio entre ", nota1, 'y', nota2, 'es', promedio)

"""## Ejercicio 8:
 
Escriba un programa que se utilizará para decidir si un alumno ha aprobado o no. Para ser aprobado, todos los promedios del alumno deben ser superiores a 7. Considere que el alumno cursa
sólo tres asignaturas, y que la calificación de cada una de ellas se almacena en las siguientes variables: materia1, materia2 y materia3.
"""

materia1_str = input('Ingrese la nota de la primer materia: ')
materia1 = int(materia1_str)

materia2_str = input('Ingrese la nota de la segunda materia: ')
materia2 = int(materia2_str)

materia3_str = input('Ingrese la nota de la tercer materia: ')
materia3 = int(materia3_str)

promedio = (materia1 + materia2 + materia3)/3

if (promedio>7):
  print('El alumno esta aprobado')
else :
  print('El alumno esta desaprobado')

"""## Ejercicio 9:

Escriba un programa que lea input del usuario: cantidad de días, horas, minutos y segundos y que en base a esos datos, calcule el total en segundos.
"""

dias = int(input("Ingresa la cantidad de días: "))
horas = int(input("Ingresa la cantidad de horas: "))
minutos = int(input("Ingresa la cantidad de minutos: "))
segundos = int(input("Ingresa la cantidad de segundos: "))

total_segundos = segundos + (minutos * 60) + (horas * 3600) + (dias * 86400)

print("El total de segundos es:", total_segundos)

"""# Ejercicio 10:

Haga un programa que pregunte por el precio de una mercaderia y el porcentaje de descuento de la misma y que calcule el importe del descuento y el precio a pagar.
"""

mercaderia= int(input('Ingrese el precio de la mercaderia: '))
porcentajeDesc= int(input('Ingrese el porcentaje de descuento: '))

importeDelDescuento = mercaderia * porcentajeDesc / 100
totalPagar = mercaderia - importeDelDescuento

print('El valor del decuento es: ', importeDelDescuento)
print('El total a pagar es: ', totalPagar)

"""## Ejercicio 11:

El alquiler de un auto cuesta `$3000` por día y `$220` por cada kilometro recorrido. Escriba un programa que calcule el valor a pagar dependiendo del número de días alquilado y de km total recorridos. 

Verifique su programa calculando el importe a pagar por un alquiler de 10 días y 400 kilometros recorridos en esos 10 días. Pruebe otros ejemplos. 

"""

valorAlquiler= 3000
valorKilometro= 220

dias=int(input('Ingrese el numero de dias alquilados: '))
km=int(input('Ingrese la cantidad de km recorridos: '))

totalPagar= (dias*valorAlquiler)+(km*valorKilometro)

print('El valor total a pagar es: ',totalPagar)

"""## Ejercicio 12:

Crea un programa que calcule el área de un rectángulo.
"""

base = float(input('Ingrese el valor de la base del rectangulo: '))
altura = float(input('Ingrese el valor de la altura del rectangulo: '))

area = base * altura

print('El area del rectangulo de ', base, 'x',altura,'es',area)